### ISSUE TITLE
Reescrever sessão Sobre

### ISSUE THREAD

**Issue by cecivieira** [pyladiesrecife/site#3]
Contextualizar a sessão Sobre para a PyLadies Recife e atualizar informações

**Comment by tiidadavena** [comment]
**Sugestão de texto**

Capítulo das PyLadies em Recife-PE, que busca integrar mulheres e pessoas não-binárias na linguagem de programação Python no contexto recifense. Somos uma comunidade que tem por base a colaboração, diversidade e inclusão de pessoas em tecnologia.

**Comment by dinizluiza** [comment]
estou trabalhando

**Comment by dinizluiza** [comment]
PR criado
