### ISSUE TITLE
Remover itens da pasta `img/about`

### ISSUE THREAD

**Issue by tiidadavena** [pyladiesrecife/site#36]
Atualizar as imagens que estão dentro da pasta de `img/about` com as imagens das pessoas integrantes do PyLadies Recife.

![image](https://user-images.githubusercontent.com/12106738/193948400-75f12f84-963d-4456-8ced-04e7f4dae7cf.png)

**Comment by naanadr** [comment]
Não entra em conflito com a issue #37 ?

**Comment by bela975** [comment]
pegamos!

**Comment by bela975** [comment]
pegamos!
