### ISSUE TITLE
Adicionar link para Código de Conduta e Manifesto pela Diversidade

### ISSUE THREAD

**Issue by cecivieira** [pyladiesrecife/site#4]
No menu, adicionar item que englobe links para :

Código de Conduta - https://github.com/pyladies-brazil/codigo-de-conduta
Manifesto - https://github.com/pyladies-brazil/manifesto

**Comment by gabriias** [comment]
Essas infos já estão na aba de valores e missão, acredito que essa issue pode ser fechada.

**Comment by naanadr** [comment]
concordo ctg @gabriias , vou fechar o PR #68  e essa issue
