### ISSUE TITLE
Menu não funciona na versão mobile

### ISSUE THREAD

**Issue by naanadr** [pyladiesrecife/site#45]
Tentei acessar o site na versão mobile e o menu que fica em cima não está funcionando. 

![image](https://user-images.githubusercontent.com/21251472/194430830-e7a0832c-9c6b-4dcf-aaa6-464393e65a21.png)

Não para ver o problema, mas estou reportando para que possamos estudar o que aconteceu.

**Comment by iMaary** [comment]
não consegui reproduzir o bug

**Comment by naanadr** [comment]
Fechando a issue pq o erro aparentemente foi local
