### ISSUE TITLE
Adicionar apresentação que explica um pouco sobre o PyLadies Brasil

### ISSUE THREAD

**Issue by naanadr** [pyladiesrecife/site#47]
Como a descrição do vídeo fala: 
```
A Débora Azevedo foi uma das palestrantes da PyCon Africa em 2020 e compartilhou a experiência da trajetória das PyLadies Brasil como maior comunidade do mundo, em número de capítulos (somos 41 capítulos em todo o território nacional). 
``` 

Por ser ser uma palestra ao meu ver relevante e que deveria ser assitida por todes, acho que poderiamos colocar em nosso site uma referência a ela.

Link: https://youtu.be/_lnVSlI2XWs

**Comment by g-101** [comment]
posso pegar esse?

**Comment by tiidadavena** [comment]
@g-101 seria massa se fosse nesse formato: 
![image](https://user-images.githubusercontent.com/12106738/194712752-97516e28-76a7-41b1-9b10-41e55b7a0f9c.png)

**Comment by tiidadavena** [comment]
Arquivo para o ícone de **link**:

![akar-icons_link-chain](https://user-images.githubusercontent.com/12106738/194712775-bc93e2ac-c54c-49f7-857b-d72184a23980.svg)
