### ISSUE TITLE
Alterar texto

### ISSUE THREAD

**Issue by nathaliavc** [pyladiesrecife/site#50]
Remover referências ao PyLadies Ribeirão Preto do site e trocar por PyLadies Recife

**Comment by nathaliavc** [comment]
seguir as especificações do figma

**Comment by nathaliavc** [comment]
já trabalhando

**Comment by naanadr** [comment]
@nathaliavc tu pode explicar melhor qual texto seria e onde? Para ajudar na hora de revisar o teu PR.

**Comment by nathaliavc** [comment]
@naanadr, a alteração se deve ao site ter "Ribeirão Preto" ou "RP" em diversos textos ao invés de "Recife", estamos trabalhando na mudança desses

**Comment by naanadr** [comment]
@nathaliavc atualizei a descrição da issue com o que você falou, se precisar de algum complemento, pode editar a issue.

**Comment by nathaliavc** [comment]
@dinizluiza trabalhou nessa issue e abriu um pull request

**Comment by naanadr** [comment]
o pull request deve ter ido para o repositório do pyladies rp

**Comment by dinizluiza** [comment]
PR criado
